server:
  port: 8004
spring:
  application:
    name: operate-redis-2-8004
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  data:
    redis:
      host: localhost
      port: 6379
      password: 111111
      timeout: 10000
      database: 2
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
management:
  endpoints:
    web:
      exposure:
        include: "*"