server:
  port: 8003
spring:
  application:
    name: operate-redis-1-8003
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  data:
    redis:
      host: localhost
      port: 6379
      password: 111111
      timeout: 10000
      database: 1
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
management:
  endpoints:
    web:
      exposure:
        include: "*"