server:
  port: 8002

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: 111111
      database: 2
      timeout: 10000
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0