server:
  port: 8051
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  redis:
    host: localhost
    port: 6379
    password: 111111
    timeout: 10000
    database: 2
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0